export { setupAntd } from './antd'
export { setupCustomComponents } from './customComponents'
export { installProviders } from './providers'
export { setupDirectives } from './directives'
export { confirm } from './confirm'
